alter table language alter column name set data type varchar(255);
alter table subject_capsule alter column name set data type varchar(255);
alter table subject_capsule alter column name set default null;
CREATE SEQUENCE learningnode_id_seq OWNED BY learningnode.id;
alter table learningnode alter column id set default nextval('learningnode_id_seq');
alter table learningnode alter column parent_node drop not null;
alter table learningnode alter column name set data type varchar(255);
CREATE SEQUENCE solution_id_seq OWNED BY solution.id;
alter table solution alter column id set default nextval('solution_id_seq');
alter table solution alter column solution_media drop not null;
alter table ques_option alter column option_media drop not null;
alter table question alter column ques_media drop not null;
alter table test alter column name set data type varchar(255);
CREATE SEQUENCE test_id_seq OWNED BY test.id;
alter table test alter column id set default nextval('test_id_seq');
alter table practicetest alter column name set data type varchar(255);
alter table plan alter column name set data type varchar(255);
alter table plan alter column description set data type text;
alter table plan alter column language set data type integer USING (language::integer);
alter table school alter column name set data type varchar(255);
alter table school alter column code set data type varchar(255);
alter table address alter column pincode set data type varchar(10);
alter table address alter column state set data type varchar(255);
alter table address alter column district set data type varchar(255);
alter table address alter column taluk set data type varchar(255);
alter table address alter column post set data type varchar(255);
alter table phone alter column number set data type varchar(255);
alter table phone alter column code set data type varchar(255);
alter table person alter column first_name set data type varchar(255);
alter table person alter column last_name set data type varchar(255);
alter table student_profile alter column language set data type integer USING (language::integer);
alter table subscribed_plan alter column bought_on set data type timestamp USING current_date + bought_on;
alter table subscribed_plan alter column first_day set data type timestamp USING current_date + first_day;
alter table subscribed_plan alter column last_day set data type timestamp USING current_date + last_day;