app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:8002/postgres
    username: postgres
    password: Welcome@123
    pool-size: 30

server:
  port: 8090

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB

logging:
  level:
    root: DEBUG
    org:
      springframework:
        web: DEBUG
        jdbc:
          core: TRACE

custom:
  planId: 1
  schoolId: 1
  languageId: 1
